### PR TITLE
Add new -transform option: keep

### PR DESCRIPTION
**Pull request by arp242**
To just keep the original values.

### CODE REVIEW

**Comment by fatih** [comment]
Hi @arp242 

What's the use case for this transform option?

**Comment by arp242** [comment]
When you just want to add json tags or whatnot and not transform anything. It’s come up a few times over the years.

**Comment by fatih** [comment]
Do you mean if you just want to use the existing field names without any transforming? That's an interesting usecase when you think that Go names are usually as camelcase or pascalcase.  Can you rebase your changes if possible? Otherwise I can add it myself.

**Comment by arp242** [comment]
Yeah but there are some cases when you want tag name to be the same as the Go struct name. I can’t recall the exact scenario(s) right now from the top of my head.

I’m currently camping around Ireland and only have email access in my phone, abd can’t rebase until I’m back in a few weeks. Feel free to just add it.

**Comment by fatih** [comment]
Thanks for the explanation. Added with #44

**Pull request closed without merging**
