### PR TITLE
feat: -file param support regular path

### PR DESCRIPTION
**Pull request by ShuaiGao**
In my project, a also need to gen code with this tool. i want to use regular path match files.

by this change, can use tool by command:

```sh
gomodifytags -file "pkg/gen/api/*pb.go" -all -add-tags form -w -quiet -skip-unexported
```

### CODE REVIEW

**Comment by ShuaiGao** [comment]
bshit......

**Comment by ShuaiGao** [comment]
is ok by the command:
```sh
gomodifytags -all -add-tags form -w -quiet -skip-unexported  -file pkg/gen/api/*pb.go
```

**Comment by ShuaiGao** [comment]
I might be right，then i reopened it. Can someone help me?

**Comment by anurag925** [comment]
@ShuaiGao  https://github.com/fatih/gomodifytags/pull/110 i also added a similar feature with less intrusion.
Basically this will generate for an entire dir if all are go files else it will throw error.

not just go files but any file written in go formate
i can add a pattern to filter files but i dont thik that is going to be use case for many

**Pull request closed without merging**
